=== Roaham/NClass/marcas/DTD/pr6.dtd
<!ELEMENT pedido (cliente, direccion, items)>
    <!ELEMENT items (item+)>
    <!ELEMENT item (nombre, precio)>
    <!ATTLIST item
        numero CDATA #REQUIRED>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT cliente (#PCDATA)>
    <!ELEMENT direccion (#PCDATA)>
    <!ELEMENT precio (#PCDATA)>

=== Roaham/NClass/marcas/DTD/pr6.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pedido SYSTEM "pr6.dtd">
<pedido>
    <cliente>Gabriela Romero</cliente>
    <direccion>C/Area del Triunfo, Granada</direccion>
    <items>
        <item numero="4">
            <nombre>Hamburguesa de bacon y queso</nombre> <precio>28</precio>
        </item>
        <item numero="3">
            <nombre>Refresco de naranja sin az√∫car</nombre> <precio>9</precio>
        </item>
    </items>
</pedido>
