=== Roaham/NClass/marcas/XML/xsd1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="productos">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded">
        
        <xs:element name="raton">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="codigo" type="xs:string"/>
              <xs:element name="descripcion" type="xs:string" minOccurs="0"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="teclado">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="codigo" type="xs:string"/>
              <xs:element name="descripcion" type="xs:string" minOccurs="1"/>
              <xs:element name="peso" type="xs:string" minOccurs="0"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

      </xs:choice>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== Roaham/NClass/marcas/XML/xml1.xml
<?xml version="1.0" encoding="UTF-8"?>
<productos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd1.xsd">
           
  <raton>
    <codigo>RAT-01</codigo>
    <descripcion>Óptico inalámbrico</descripcion>
  </raton>

  <teclado>
    <codigo>TEC-02</codigo>
    <descripcion>Mecánico RGB</descripcion> <peso>850g</peso> </teclado>

</productos>
